#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef VBOTPHONESDK_SWIFT_H
#define VBOTPHONESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CallKit;
@import Foundation;
@import ObjectiveC;
#endif

#import <VBotPhoneSDK/VBotPhoneSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VBotPhoneSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class VBotHotline;
SWIFT_CLASS("_TtC12VBotPhoneSDK10HotlineRes")
@interface HotlineRes : NSObject
@property (nonatomic, readonly) NSInteger status;
@property (nonatomic, readonly) NSInteger error;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSArray<VBotHotline *> * _Nonnull data;
/// Hàm log response API
- (void)logResponse;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Class kết quả cho Objective-C
SWIFT_CLASS("_TtC12VBotPhoneSDK14VBotCallIntent")
@interface VBotCallIntent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull number;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VBotCallLogErrorCode, open) {
  VBotCallLogErrorCodeCallAnswered = 1000,
  VBotCallLogErrorCodeBusyOrDecline = 1001,
  VBotCallLogErrorCodeNoAnswer = 1002,
  VBotCallLogErrorCodeCallerHungUp = 1003,
  VBotCallLogErrorCodeConnectionError = 1004,
  VBotCallLogErrorCodeCallDeclined = 9996,
  VBotCallLogErrorCodeMissedCallTimeout = 9997,
  VBotCallLogErrorCodeMissedCallOther = 9998,
  VBotCallLogErrorCodeUnknownError = 9999,
};

SWIFT_CLASS("_TtC12VBotPhoneSDK14VBotCallReport")
@interface VBotCallReport : NSObject
@property (nonatomic, copy) NSString * _Nonnull endTime;
@property (nonatomic) BOOL status;
@property (nonatomic, copy) NSString * _Nonnull order;
@property (nonatomic, copy) NSString * _Nonnull callerNumber;
@property (nonatomic, copy) NSString * _Nonnull duration;
@property (nonatomic, copy) NSString * _Nonnull callID;
@property (nonatomic, copy) NSString * _Nonnull startTime;
@property (nonatomic, copy) NSString * _Nonnull ringingTime;
@property (nonatomic, copy) NSString * _Nonnull errorType;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;
SWIFT_CLASS("_TtC12VBotPhoneSDK10VBotConfig")
@interface VBotConfig : NSObject
@property (nonatomic, readonly) BOOL supportPopupCall;
@property (nonatomic, readonly) BOOL includesCallsInRecents;
@property (nonatomic, readonly, copy) NSData * _Nullable iconTemplateImageData;
- (nonnull instancetype)initWithSupportPopupCall:(BOOL)supportPopupCall includesCallsInRecents:(BOOL)includesCallsInRecents iconTemplateImageData:(NSData * _Nullable)iconTemplateImageData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12VBotPhoneSDK10VBotCrypto")
@interface VBotCrypto : NSObject
+ (NSString * _Nullable)encryptWithNumber:(NSString * _Nonnull)number name:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
+ (VBotCallIntent * _Nullable)decrypt:(NSString * _Nonnull)hexEncoded SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, VBotEndCallReason, open) {
  VBotEndCallReasonTimeOut = 1004,
  VBotEndCallReasonNotReadyForStartCall = 2002,
  VBotEndCallReasonMicrophonePermissionDenied = 9999,
  VBotEndCallReasonInvalidPhoneNumber = 2004,
  VBotEndCallReasonNoDataFromServer = 2005,
  VBotEndCallReasonEndCallBeforeServerStartCall = 2006,
  VBotEndCallReasonNoSIPCallCreated = 2007,
  VBotEndCallReasonDataInvalid = 2008,
  VBotEndCallReasonNoVBotSIPUser = 2009,
  VBotEndCallReasonAuthenticatedFailed = 2010,
  VBotEndCallReasonAnotherCallInProgress = 2011,
  VBotEndCallReasonNormaly = 1000,
  VBotEndCallReasonDecline = 2013,
  VBotEndCallReasonTemporarilyUnavailable = 2014,
  VBotEndCallReasonBusy = 1001,
  VBotEndCallReasonReportNewIncomingCallFailed = 2016,
  VBotEndCallReasonAlertDataNotFound = 2017,
  VBotEndCallReasonNoPushToken = 1018,
  VBotEndCallReasonSetupSIPEndpointFailed = 2019,
  VBotEndCallReasonRequestCallKitActionFailed = 2020,
  VBotEndCallReasonNoSIPAccount = 2022,
  VBotEndCallReasonIncomingCallTimeout = 2023,
  VBotEndCallReasonUnknownError = 9996,
};

SWIFT_CLASS("_TtC12VBotPhoneSDK11VBotHotline")
@interface VBotHotline : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull phoneNumber;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12VBotPhoneSDK20VBotLocalizedStrings")
@interface VBotLocalizedStrings : NSObject
@property (nonatomic, copy) NSString * _Nonnull call_btn_messsage;
@property (nonatomic, copy) NSString * _Nonnull call_btn_mute;
@property (nonatomic, copy) NSString * _Nonnull call_btn_speaker;
@property (nonatomic, copy) NSString * _Nonnull call_calling;
@property (nonatomic, copy) NSString * _Nonnull call_connecting;
@property (nonatomic, copy) NSString * _Nonnull call_ringing;
@property (nonatomic, copy) NSString * _Nonnull call_title_outgoing;
@property (nonatomic, copy) NSString * _Nonnull call_title_incomming;
@property (nonatomic, copy) NSString * _Nonnull call_weak_signal;
@property (nonatomic, copy) NSString * _Nonnull call_end;
@property (nonatomic, copy) NSString * _Nonnull call_refused;
@property (nonatomic, copy) NSString * _Nonnull call_busy;
@property (nonatomic, copy) NSString * _Nonnull call_temporarily_unavailable;
@property (nonatomic, copy) NSString * _Nonnull call_failed_api;
@property (nonatomic, copy) NSString * _Nonnull call_failed_no_connection;
@property (nonatomic, copy) NSString * _Nonnull call_lost_connection;
@property (nonatomic, copy) NSString * _Nonnull call_permission_btn_allow;
@property (nonatomic, copy) NSString * _Nonnull call_permission_btn_deny;
@property (nonatomic, copy) NSString * _Nonnull call_permission_btn_setting;
@property (nonatomic, copy) NSString * _Nonnull call_permission_btn_skip;
@property (nonatomic, copy) NSString * _Nonnull call_permission_microphone_content;
@property (nonatomic, copy) NSString * _Nonnull call_permission_microphone_demied_content;
@property (nonatomic, copy) NSString * _Nonnull call_permission_microphone_demied_title;
@property (nonatomic, copy) NSString * _Nonnull call_permission_microphone_title;
- (nonnull instancetype)initWithCall_btn_messsage:(NSString * _Nonnull)call_btn_messsage call_btn_mute:(NSString * _Nonnull)call_btn_mute call_btn_speaker:(NSString * _Nonnull)call_btn_speaker call_calling:(NSString * _Nonnull)call_calling call_connecting:(NSString * _Nonnull)call_connecting call_end:(NSString * _Nonnull)call_end call_failed_api:(NSString * _Nonnull)call_failed_api call_failed_no_connection:(NSString * _Nonnull)call_failed_no_connection call_lost_connection:(NSString * _Nonnull)call_lost_connection call_permission_btn_allow:(NSString * _Nonnull)call_permission_btn_allow call_permission_btn_deny:(NSString * _Nonnull)call_permission_btn_deny call_permission_btn_setting:(NSString * _Nonnull)call_permission_btn_setting call_permission_btn_skip:(NSString * _Nonnull)call_permission_btn_skip call_permission_microphone_content:(NSString * _Nonnull)call_permission_microphone_content call_permission_microphone_demied_content:(NSString * _Nonnull)call_permission_microphone_demied_content call_permission_microphone_demied_title:(NSString * _Nonnull)call_permission_microphone_demied_title call_permission_microphone_title:(NSString * _Nonnull)call_permission_microphone_title call_refused:(NSString * _Nonnull)call_refused call_busy:(NSString * _Nonnull)call_busy call_temporarily_unavailable:(NSString * _Nonnull)call_temporarily_unavailable call_ringing:(NSString * _Nonnull)call_ringing call_title_outgoing:(NSString * _Nonnull)call_title_outgoing call_title_incomming:(NSString * _Nonnull)call_title_incomming call_weak_signal:(NSString * _Nonnull)call_weak_signal OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12VBotPhoneSDK9VBotPhone")
@interface VBotPhone : NSObject <CXCallObserverDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VBotPhone * _Nonnull sharedInstance;)
+ (VBotPhone * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum AVAudioSessionRecordPermission microphonePermissionGranted;
@property (nonatomic, copy) NSString * _Nullable pushKitToken;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol VBotPhoneDelegate;
@interface VBotPhone (SWIFT_EXTENSION(VBotPhoneSDK))
- (void)addDelegate:(id <VBotPhoneDelegate> _Nonnull)delegate;
- (void)removeDelegate:(id <VBotPhoneDelegate> _Nonnull)delegate;
@end

@class CXCallObserver;
@class CXCall;
@interface VBotPhone (SWIFT_EXTENSION(VBotPhoneSDK))
- (void)callObserver:(CXCallObserver * _Nonnull)callObserver callChanged:(CXCall * _Nonnull)call;
@end

@class NSError;
@class PKPushPayload;
@class NSUUID;
@interface VBotPhone (SWIFT_EXTENSION(VBotPhoneSDK))
/// Khởi tạo và cấu hình VBot Client với các thông số cần thiết
/// \param config Cấu hình cho VBot Client. Nếu không được chỉ định, sẽ sử dụng cấu hình mặc định
///
- (void)setupWith:(VBotConfig * _Nonnull)config;
/// Cập nhật cấu hình cho VBot Client
/// \param config Đối tượng VBotConfig chứa các thông số cấu hình mới
///
- (void)setConfigWithConfig:(VBotConfig * _Nonnull)config;
/// Lấy cấu hình hiện tại của VBot Client
///
/// returns:
/// Đối tượng VBotConfig chứa các thông số cấu hình hiện tại
- (VBotConfig * _Nonnull)getConfig SWIFT_WARN_UNUSED_RESULT;
/// Lấy các chuỗi localization hiện tại
///
/// returns:
/// Đối tượng TeleLocalizedStrings chứa các chuỗi localization
- (VBotLocalizedStrings * _Nonnull)getLocalizedStrings SWIFT_WARN_UNUSED_RESULT;
/// Kết nối VBot Client
- (void)connectWithToken:(NSString * _Nonnull)token pushkitToken:(NSString * _Nonnull)pushkitToken completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Ngắt kết nối VBot Client
- (void)disconnectWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Lấy trạng thái kết nối của tài khoản
- (BOOL)isUserConnected SWIFT_WARN_UNUSED_RESULT;
/// Lấy tên hiển của tài khoản
- (NSString * _Nullable)userDisplayName SWIFT_WARN_UNUSED_RESULT;
/// Lấy CLient Token của tài khoản
- (NSString * _Nullable)userToken SWIFT_WARN_UNUSED_RESULT;
/// Lấy danh sách hotline
- (void)getHotlinesWithCompletion:(void (^ _Nonnull)(NSArray<VBotHotline *> * _Nullable, NSError * _Nullable))completion;
/// Lấy thông tin người gọi từ chuỗi mã hóa
- (VBotCallIntent * _Nullable)getCallIntentFromUserActivity:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
/// Gọi đi
- (void)startOutgoingCallWithDisplayName:(NSString * _Nonnull)displayName number:(NSString * _Nonnull)number hotline:(NSString * _Nonnull)hotline externalCallId:(NSString * _Nullable)externalCallId completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
- (void)startIncomingCallWithPayload:(PKPushPayload * _Nonnull)payload completion:(void (^ _Nonnull)(void))completion;
/// Quay trở lại màn hình cuộc gọi nếu có cuộc gọi đang hoạt động
- (void)returnToCallVCIfNeeded;
/// Ẩn màn hình cuộc gọi
- (void)hideCallVCIfNeeded;
/// Kiểm tra xem có call hay không
- (BOOL)hasActiveCall SWIFT_WARN_UNUSED_RESULT;
/// Kết thức cuộc gọi
- (void)endCallWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Tắt Microphone
- (void)muteCall;
/// Giữ cuộc gọi
- (void)holdCallWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Kiểm tra có thiết bị âm thanh Bluetooth khôngg
- (BOOL)hasAudioBluetooth SWIFT_WARN_UNUSED_RESULT;
/// Kiểm tra loa ngoài có bật không
- (BOOL)isSpeakerOn SWIFT_WARN_UNUSED_RESULT;
/// Bật/Tắt loa ngoài
- (void)onOffSpeaker;
/// Kiểm tra call có bị giữ không
- (BOOL)isCallHold SWIFT_WARN_UNUSED_RESULT;
/// Kiểm ra cuộc gọi có mute không
- (BOOL)isCallMute SWIFT_WARN_UNUSED_RESULT;
/// Gửi DTMF
- (void)sendDTMFWithDigit:(NSString * _Nonnull)digit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Kết thức cuộc gọi
- (void)endCallByPushkitWithUuid:(NSUUID * _Nonnull)uuid completion:(void (^ _Nonnull)(void))completion;
@end

/// Protocol định nghĩa các phương thức delegate cho VBot
SWIFT_PROTOCOL("_TtP12VBotPhoneSDK17VBotPhoneDelegate_")
@protocol VBotPhoneDelegate
@optional
/// Được gọi khi trạng thái của cuộc gọi thay đổi
- (void)callStateChangedWithState:(VBotCallState)state;
/// Được gọi khi một cuộc gọi đi mới bắt đầu
- (void)callStarted;
/// Được gọi khi người dùng chấp nhận một cuộc gọi đến
- (void)callAccepted;
/// Được gọi khi cuộc gọi kết thúc
- (void)callEndedWithReason:(enum VBotEndCallReason)reason;
/// Được gọi khi trạng thái microphone
- (void)microphonePermissionWithStatus:(enum AVAudioSessionRecordPermission)status;
/// Được gọi khi trạng thái microphone thay đổi
- (void)callMuteStateDidChangeWithMuted:(BOOL)muted;
/// Mở màn hình call
- (void)showCallVC;
/// Quay lại màn hình call
- (void)returnToCallVC;
/// Ẩn màn hình call
- (void)hideCallVC;
/// Mất mạng
- (void)networkIsUnreachable;
/// Mạng thay đổi
- (void)internetConnectionChanged;
/// Được gọi khi nhận được externalCallId (1 lần duy nhất khi bắt đầu cuộc gọi)
- (void)didReceiveExternalCallId:(NSString * _Nonnull)externalCallId;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
